#!/bin/bash
sudo mdutil -i off -a

sudo mkdir /Applications/empty_dir /Applications/yourdirectory
sudo mv /Applications/Xcode_11* /Applications/yourdirectory/
sudo rsync -a --delete /Applications/empty_dir/    /Applications/yourdirectory/ &
hdiutil create -type SPARSE -fs 'Case-sensitive Journaled HFS+' -size 250g ~/android.dmg.sparseimage
mountAndroid() { hdiutil attach ~/android.dmg.sparseimage -mountpoint /Volumes/android; }
mountAndroid
ulimit -S -n 20480

mkdir ~/bin
PATH=~/bin:$PATH
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo
git config --global user.name "Apon77"
git config --global user.email "khalakuzzamanapon5@gmail.com"
git config --global color.ui true

brew install ccache &
cd /Volumes/android
repo init --depth=1 -u git://github.com/AospExtended/manifest.git -b 11.x -g default,-notdefault,-device,-mips
git clone https://github.com/Apon77Lab/android_.repo_local_manifests.git -b aex .repo/local_manifests
cd .repo/local_manifests
git cherry-pick 0248b271aac34cdcd0aeb641e92a459fdc467502
cd -
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30

cd build/soong/
git fetch https://github.com/LineageOS/android_build_soong
git cherry-pick 7e5cbc10ec376269c29ef6c30ed60db592af7985
sudo xcode-select -s /Applications/Xcode_12.app/Contents/Developer
cd -
cd device/xiaomi/mido
git fetch https://github.com/RahifM/device_xiaomi_mido
git cherry-pick 8cc947b40d062c4621c6cde969c3de52443b1c4d
cd -

. build/envsetup.sh
lunch aosp_mido-user
export CCACHE_DIR=~/aosp/untitled/aex/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
make api-stubs-docs -j 24
curl --upload-file out/target/product/mido/*.zip https://free.keep.sh || echo failed to upload
