#!/bin/bash
sudo mkdir /Applications/empty_dir /Applications/yourdirectory
sudo mv /Applications/Xcode_11* /Applications/yourdirectory/
which rsync
/usr/bin/rsync --version
brew install rsync
/usr/local/Cellar/rsync/3.2.3/bin/rsync --version
/usr/local/Cellar/rsync/3.2.3/bin/rsync --version
rsync --version
sudo rsync -a --delete /Applications/empty_dir/    /Applications/yourdirectory/
ls /Applications
