name: aosp
on: push
defaults:
  run:
    shell: bash

jobs:
  job:
    runs-on: macos-latest
    strategy:
      matrix: 
        run: ['run1', 'run2']
    steps:
    - uses: actions/checkout@v2
    - run: echo Run ${{ matrix.run }}
    - run: echo $0
    - run: source var
    - run: echo $hi
