name: aosp
on: push

jobs:
  job1:
    name: api, system
    runs-on: macos-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - run: ./volume
    - uses: aochmann/actions-download-artifact@1.0.4
      continue-on-error: true
      with:
        name: ccache
        latest: true
        path: /Volumes/android/ccache
        repo: mr-beast77/am
    - continue-on-error: true
      run: ./sync
    - continue-on-error: true
      run: |
       source common
       make api-stubs-docs -j6
    - continue-on-error: true
      run: |
       source common
       make system-api-stubs-docs -j6
    - uses: actions/upload-artifact@v2
      continue-on-error: true
      with:
        name: ccache
        path: /Volumes/android/ccache


  job2:
    name: bootimage, test-api, init
    runs-on: macos-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - run: ./volume
    - uses: aochmann/actions-download-artifact@1.0.4
      continue-on-error: true
      with:
        name: ccache
        latest: true
        path: /Volumes/android/ccache
        repo: mr-beast77/am
    - continue-on-error: true
      run: ./sync
    - continue-on-error: true
      run: |
       source common
       make bootimage -j6
    - continue-on-error: true
      run: |
       source common
       make test-api-stubs-docs -j6
    - continue-on-error: true
      run: |
       source common
       make init -j6
    - uses: actions/upload-artifact@v2
      continue-on-error: true
      with:
        name: ccache
        path: /Volumes/android/ccache

  job3:
    name: app_process, services
    runs-on: macos-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - run: ./volume
    - uses: aochmann/actions-download-artifact@1.0.4
      continue-on-error: true
      with:
        name: ccache
        latest: true
        path: /Volumes/android/ccache
        repo: mr-beast77/am
    - continue-on-error: true
      run: ./sync
    - continue-on-error: true
      run: |
       source common
       make app_process -j6
    - continue-on-error: true
      run: |
       source common
       make services -j6
    - uses: actions/upload-artifact@v2
      continue-on-error: true
      with:
        name: ccache
        path: /Volumes/android/ccache

  job4:
    name: framework, framework-res
    runs-on: macos-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - run: ./volume
    - uses: aochmann/actions-download-artifact@1.0.4
      continue-on-error: true
      with:
        name: ccache
        latest: true
        path: /Volumes/android/ccache
        repo: mr-beast77/am
    - continue-on-error: true
      run: ./sync
    - continue-on-error: true
      run: |
       source common
       make framework -j6
    - continue-on-error: true
      run: |
       source common
       make framework-res -j6
    - uses: actions/upload-artifact@v2
      continue-on-error: true
      with:
        name: ccache
        path: /Volumes/android/ccache

  job5:
    name: runtime,libbinder
    runs-on: macos-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - run: ./volume
    - uses: aochmann/actions-download-artifact@1.0.4
      continue-on-error: true
      with:
        name: ccache
        latest: true
        path: /Volumes/android/ccache
        repo: mr-beast77/am
    - continue-on-error: true
      run: ./sync
    - continue-on-error: true
      run: |
       source common
       make libandroid_runtime -j6
    - continue-on-error: true
      run: |
       source common
       make libbinder -j 6
    - uses: actions/upload-artifact@v2
      continue-on-error: true
      with:
        name: ccache
        path: /Volumes/android/ccache

#####################################################

#####################################################

  final:
    name: aex
    needs: [job1, job2, job3, job4, job5]
    runs-on: macos-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - run: ./volume
    - uses: actions/download-artifact@v2
      continue-on-error: true
      with:
        name: ccache
        path: /Volumes/android/ccache
    - continue-on-error: true
      run: ./sync
    - continue-on-error: true
      timeout-minutes: 290
      run: |
       source final
       make aex -j 9
    - uses: actions/upload-artifact@v2
      continue-on-error: true
      with:
        name: ccache
        path: /Volumes/android/ccache
        retention-days: 2
