name: aosp
on: push

jobs:
  job:
    runs-on: macos-latest
    strategy:
      matrix: 
        run: ['api-stubs-docs', 'hiddenapi-lists-docs', 'system-api-stubs-docs', 'test-api-stubs-docs', 'aex']
    steps:
    - uses: actions/checkout@v2
    - run: |
       hi=ok
       echo $hi
    - run: echo common
    - run: echo make ${{ matrix.run}}
