name: aosp
on: push
jobs:
  job:
    runs-on: macos-latest
    shell: bash
    strategy:
      matrix: 
        run: ['run1', 'run2']
    steps:
    - run: echo Run ${{ matrix.run }}
    - run: echo $0
    - run: source var
    - run: echo $hi
