name: artifacts
on: push

jobs:
  job:
    name: aosp
    runs-on: macos-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix: 
        #run: ['com.android.media', 'api-stubs-docs', 'system-api-stubs-docs', 'test-api-stubs-docs', 'aex']
        #run: ['aex']
        run: ['api-stubs-docs', 'aex']
    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p path/to/artifact

    - uses: actions/download-artifact@v2
        with: my-artifact
        path: path/to/artifact

    - run: ls path/to/artifact

    - run: echo hello > path/to/artifact/world.txt

    - run: echo 3nd > path/to/artifact/3nd.txt

    - run: mkfile -n 1g path/to/artifact/1g

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: path/to/artifact/
        retention-days: 2



  delete:
    name: delete artifacts
    runs-on: ubuntu-20.04
    needs: [job]
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: my-artifact

