name: aosp
on: push

jobs:
  job3:
    name: app_process, services
    runs-on: macos-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - run: ./volume
    - uses: aochmann/actions-download-artifact@1.0.4
      continue-on-error: true
      with:
        name: ccache
        latest: true
        path: /Volumes/android/ccache
        repo: mr-beast77/am
    - continue-on-error: true
      run: ./sync
    - continue-on-error: true
      run: |
       source common
       make app_process
    - continue-on-error: true
      run: |
       source common
       make services
    - uses: actions/upload-artifact@v2
      continue-on-error: true
      with:
        name: ccache
        path: /Volumes/android/ccache
